# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Article.create([
  { :title => "Share page", :photo_id => nil, :blurb => "<p>This is share page</p>\r\n<p><img src=\"/system/images/BAhbBlsHOgZmSSJbMjAxMi8wMy8yNy8xNF8wNl81MV81OTVfZWFjYWI3NDgzNjA1Mzc2NWRiOWUwMDkyMGM1MzI1MWYzMWUwMWQzODE1MWZlX05HUGtpTl9mdzU1NC5qcGcGOgZFVA/eacab74836053765db9e00920c53251f31e01d38151fe-NGPkiN_fw554.jpg\" title=\"Eacab74836053765db9e00920c53251f31e01d38151fe Ng Pki N Fw554\" alt=\"Eacab74836053765db9e00920c53251f31e01d38151fe Ng Pki N Fw554\" rel=\"225x255\" width=\"510\" height=\"360\" /></p>", :position => 0, :created_at => "2012-03-27 02:44:08", :updated_at => "2012-03-27 06:24:39" }
])



Booking.create([
  { :choice => nil, :location => nil, :number_weeks => nil, :number_adults => nil, :number_children => nil, :created_at => nil, :updated_at => nil }
])



Post.create([
  { :name => "liusihao", :title => "It's the new post", :content => "Hello,world!!It's the new postHello,world!!It's the new postHello,world!!It's the new postHello,world!!It's the new postHello,world!!It's the new postHello,world!!It's the new postHello,world!!It's the new postHello,world!!It's the new postHello,world!!It's the new post", :created_at => "2012-03-28 05:39:34", :updated_at => "2012-03-28 05:39:34" },
  { :name => "liusihao", :title => "hahhahahah", :content => "hahhahahah\r\nI'm the test\r\nI'm the test\r\nI'm the test\r\nI'm the test\r\nI'm the test\r\nI'm the test", :created_at => "2012-03-28 05:40:01", :updated_at => "2012-03-28 05:40:01" }
])



PostTest.create([
  { :name => "haha", :title => "post test", :content => "content of post test", :created_at => "2012-03-28 07:00:39", :updated_at => "2012-03-28 07:00:39" }
])



Test.create([
  { :name => nil, :title => nil, :created_at => nil, :updated_at => nil }
])


